[package]
name = "disk_usage"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "0.3.5"

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation"
]
