import { SizeItem } from "./ui/size-item-struct.slint";
import { Style } from "./ui/style.slint";

component DiskItem inherits Rectangle {

    in property<SizeItem> size_item;
    in property<bool> cursor;

    height: 48pt;
    //width: parent.width - 16pt;
    Rectangle {
        x: 6pt;
        y: 3pt;
        width: parent.width - 12pt;
        height: parent.height - 6pt;
        background: Style.list-item-background;
        Rectangle {
            x: 0;
            y: 0;
            background: @linear-gradient(90deg, Style.list-item-background 0%, Style.size-gradient-max 100%);
            width: parent.width;
        }
        Rectangle {
            background: Style.list-item-background;
            x: parent.width * size_item.relative_size;
            y: 0;
            width: parent.width - (parent.width * size_item.relative_size);
        }
        Rectangle {
            background: Style.cursor-color;
            height: parent.height * 0.75;
            x: 0;
            y: (parent.height - self.height)/2;
            width: 3pt;
            opacity: cursor ? 1 : 0;
            animate opacity {
                duration: 300ms;
            }
        }
        Text {
            x: 10pt;
            y: 3pt;
            color: Style.text-main;
            font-family: "Segoe UI";
            font-size: 12pt;
            text: size_item.name;
        }
        Text {
            x: 10pt;
            y: 20pt;
            color: Style.text-secondary;
            font-family: "Segoe UI";
            font-size: 12pt;
            text: size_item.size_string;
        }
    }
}

export { DiskItem }
