import { SizeItem } from "./ui/size-item-struct.slint";
import { Style } from "./ui/style.slint";

component DiskItem inherits Rectangle {

    in property<SizeItem> size_item;
    in property<bool> active;

    height: 45pt;
    Rectangle {
        x: 6pt;
        y: 3pt;
        width: parent.width - 12pt;
        height: parent.height - 6pt;
        background: Style.list-item-background;
        Rectangle {
            x: 0;
            y: 0;
            background: @linear-gradient(90deg, Style.list-item-background 0%, Style.size-gradient-max 100%);
            width: parent.width;
        }
        Rectangle {
            background: Style.list-item-background;
            x: parent.width * size_item.relative_size;
            y: 0;
            width: parent.width - (parent.width * size_item.relative_size);
        }
        cursor_marker := Rectangle {
            background: Style.cursor-color;
            height: parent.height * 0.6;
            x: 0;
            y: (parent.height - self.height)/2;
            width: 3pt;
            //opacity: active ? 1 : 0;
        }
        Rectangle {
            x: 8pt;
            height: parent.height;
            width: self.height;
            // TODO: this is a bit blurry, find better icons:
            Text {
                text: size_item.is_file ? "🗋" : "🗀";
                font-family: "Segoe UI";
                font-size: 26pt;
                color: Style.text-main;
                y: 0pt;
            }
        }
        Text {
            x: 55pt;
            y: 1pt;
            color: Style.text-main;
            font-family: "Segoe UI";
            font-size: 12pt;
            text: size_item.name;
        }
        Text {
            x: 55pt;
            y: 19pt;
            color: Style.text-secondary;
            font-family: "Segoe UI";
            font-size: 12pt;
            text: size_item.size_string;
        }
    }

    states [
        active when active : {
            cursor_marker.opacity: 1;
            in {
                animate cursor_marker.opacity { duration: 50ms; }
            }
            out {
                animate cursor_marker.opacity { duration: 300ms; }
            }
        }
        inactive when !active : {
            cursor_marker.opacity: 0;
        }
    ]
}

export { DiskItem }
