global Style {
    out property<color> window-background: #000000;
    // out property<color> window-background: #1f1f1f;
    out property<color> list-item-background: #333333;
    out property<color> size-on-disk-gradient-max: #ff3333;
    out property<color> size-real-gradient-max: #ffff33;
    out property<color> text-main: #ffffff;
    out property<color> text-secondary: #cccccc;
    out property<color> scrollbar-color: #1f1f1f;
    //out property<color> cursor-color: #0078d4;
    out property<color> cursor-color: #33ffee;
}

export { Style }
